* switch from custom su-me to generic su-to-root, adapt dependencies and   menu files accordingly. * move desktop file into standard XDG hierarchy. * prefer syslog-ng over sysklogd.

diff --git a/startsyslog b/startsyslog
--- a/startsyslog
+++ b/startsyslog
@@ -1,13 +1,14 @@
 #!/bin/sh
 # startsyslog - Start syslogd and show logging messages
-# (C) Klaus Knopper Jun 2001
+# (C) 2001 Klaus Knopper <knopper@knopper.net>
 # (C) 2007 Kel Modderman <kel@otaku42.de>
-# (C) 2007 Stefan Lippers-Hollmann <s.l-h@gmx.de>
+# (C) 2007-2008 Stefan Lippers-Hollmann <s.l-h@gmx.de>
 
-PATH="/bin:/sbin:/usr/bin:/usr/sbin"
-export PATH
-
-[ "$(id -u)" -eq 0 ] || exec su-me "$0" "$@"
+if [ "$(id -u)" -ne 0 ]; then
+	[ -x "$(which su-to-root)" ] && exec su-to-root -X -c "$0" "$@"
+	printf "ERROR: $0 needs root capabilities, please start it as root.\n\n" >&2
+	exit 4
+fi
 
 if [ -x /etc/init.d/sysklogd ]; then
 	if ! invoke-rc.d sysklogd reload-or-restart; then
